name: Kali image builder
on:
  push:
    tags:
      - 'v*'
jobs:
  make-image:
    runs-on: ubuntu-latest
    name: kali-builder
    steps:
      - uses: actions/checkout@v2
      - name: Build ISO
        run: |
              sudo apt-get update
              sudo apt-get install -y xz-utils git live-build simple-cdd cdebootstrap curl debootstrap
              keyring_url="http://http.kali.org/pool/main/k/kali-archive-keyring/"
              keyring_file=$(curl -s -k $keyring_url | grep -oe "kali*.*all.deb" | sed -e 's/.*">//')
              wget -nv "$keyring_url/$keyring_file"
              livebuild_url="https://http.kali.org/kali/pool/main/l/live-build/"
              livebuild_file=$(curl -s -k $livebuild_url | grep -oe "live-build*.*all.deb" | sed -e 's/.*">//' | head -1)
              wget -nv "$livebuild_url/$livebuild_file"
              simplecdd_url="https://http.kali.org/kali/pool/main/s/simple-cdd/"
              simplecdd_file=$(curl -s -k $simplecdd_url | grep -oe "simple-cdd*.*all.deb" | sed -e 's/.*">//' | sort -r | head -1)
              wget -nv "$simplecdd_url/$simplecdd_file"
              sudo dpkg -i "$keyring_file" "$livebuild_file" "$simplecdd_file"
              release_url="https://gitlab.com/kalilinux/packages/base-files/-/raw/kali/master/etc/os-release"
              kali_version="$(curl -s -k $release_url | awk -F= '$1=="VERSION" {print $2;}' | tr -d '"' || true)"
              sudo ./build.sh \
                --distribution kali-rolling \
                --version $kali_version \
                --arch i386 \
                --verbose
              sudo xz -T $(nproc) images/kali-linux-$kali_version-live-i386.iso
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: images/kali-linux-*
