name: Kali image builder
on:
  push:
    tags:
      - 'v*'
jobs:
  make-image:
    runs-on: ubuntu-latest
    name: kali-builder
    steps:
      - uses: actions/checkout@v2
      - name: Build ISO
        run: |
              sudo apt-get update
              sudo apt-get install -y git live-build simple-cdd cdebootstrap curl
              wget https://http.kali.org/pool/main/k/kali-archive-keyring/kali-archive-keyring_2020.2_all.deb
              wget https://http.kali.org/kali/pool/main/l/live-build/live-build_20210902kali1_all.deb
              sudo dpkg -i kali-archive-keyring_2020.2_all.deb
              sudo dpkg -i live-build_20210407_all.deb
              sudo ./build.sh \
                --distribution kali-last-snapshot \
                --version 2021.4 \
                --arch amd64
              ls
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: kali.iso
