name: Kali image builder
on:
  push:
    tags:
      - 'v*'
jobs:
  make-image:
    runs-on: ubuntu-latest
    name: kali-builder
    steps:
      - uses: actions/checkout@v2
      - name: Build ISO
        run: |
              sudo apt-get update
              sudo apt-get install -y xz-utils git live-build simple-cdd cdebootstrap curl debootstrap make jetring
              sudo bash <(wget -qO- https://git.io/kali-archive-keyring.sh)
              wget https://http.kali.org/kali/pool/main/l/live-build/live-build_20210902kali1_all.deb
              sudo dpkg -i *.deb
              sudo ./build.sh \
                --distribution kali-rolling \
                --version 2021.4 \
                --arch amd64 \
                --verbose
              sudo xz -T $(nproc) images/kali-linux-2021.4-live-amd64.iso
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: images/kali-linux-2021.4-live-amd64.iso.xz
