name: Kali image builder
on:
  push:
    tags:
      - 'v*'
jobs:
  make-image:
    runs-on: ubuntu-latest
    name: kali-builder
    steps:
      - uses: actions/checkout@v2
      - name: Build ISO
        run: |
              sudo apt-get update
              sudo apt-get install -y xz-utils git live-build simple-cdd cdebootstrap curl debootstrap
              keyring_url="http://http.kali.org/pool/main/k/kali-archive-keyring/"
              keyring_file=$(curl -s -k $keyring_url | grep -oe "kali*.*all.deb" | sed -e 's/.*">//')
              wget -nv "$keyring_url/$keyring_file"
              sudo dpkg -i "$keyring_file"
              livebuild_url="https://http.kali.org/kali/pool/main/l/live-build/"
              livebuild_file=$(curl -s -k $livebuild_url | grep -oe "live-build*.*all.deb" | sed -e 's/.*">//' | head -1)
              wget -nv "$livebuild_url/$livebuild_file"
              sudo dpkg -i *.deb
              sudo ./build.sh \
                --distribution kali-rolling \
                --version 2021.4 \
                --arch amd64 \
                --verbose
              sudo xz -T $(nproc) images/kali-linux-2021.4-live-amd64.iso
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: images/kali-linux-2021.4-live-amd64.iso.xz
